theme/hud_django_v3.0/template_django_startup/DjangoHUD/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('DjangoHUDApp.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'DjangoHUDApp.views.handler404'

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/urls.py
from django.urls import path

from . import views

app_name = 'DjangoHUDApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('404/', views.error404, name='error404')
]

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/models.py
from django.db import models

# Create your models here.

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse

def index(request):
	return render(request, "pages/index.html")
	
def error404(request):
	context = {
		"appSidebarHide": 1,
		"appHeaderHide": 1,
		"appContentClass": 'p-0'
	}
	return render(request, "pages/page-error.html", context)

def handler404(request, exception = None):
	return redirect('/404/')

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark" {% block htmlAttr %}{% endblock %}>
<head>
	<meta charset="utf-8">
	<title>HUD | {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	
	<!-- ================== BEGIN core-css ================== -->
	{% load static %}
	<link href="{% static 'css/vendor.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/app.min.css' %}" rel="stylesheet">
	<!-- ================== END core-css ================== -->
	
	{% block css %}{% endblock %}
</head>
<body class="{{ bodyClass }}{% if appHeaderHide is not None %} pace-top {% endif %}" {{ bodyAttr }}>
	
	<div id="app" class="app 
		{% if appSidebarHide is not None %}app-without-sidebar{% endif %}
		{% if appSidebarCollapsed %}app-sidebar-collapsed{% endif %}
		{% if appHeaderHide is not None %}app-without-header{% endif %}
		{% if appTopNav %}app-with-top-nav{% endif %}
		{% if appContentFullHeight is not None %}app-content-full-height{% endif %}
		{% if appFooter %}app-fixed-footer{% endif %}
		{% if appBoxedLayout %}app-boxed-layout{% endif %}
	">
		{% if appHeaderHide is None %}
			{% include 'partial/header.html' %}
		{% endif %}
		
		{% if appSidebarHide is None %}
			{% include 'partial/sidebar.html' %}
		{% endif %}
		
		{% if appTopNav %}
			{% include 'partial/top-nav.html' %}
		{% endif %}
		
		<div class="app-content {{ appContentClass }}">
			{% block content %}{% endblock %}
		</div>
		
		{% include 'partial/theme-panel.html' %} 
		
		{% if appFooter %}
			{% include 'partial/footer.html' %}
		{% endif %}
	</div>

	{% include 'partial/scroll-top-btn.html' %} 
	
	{% block outter_content %}{% endblock %}

	<!-- ================== BEGIN core-js ================== -->
	<script src="{% static 'js/vendor.min.js' %}"></script>
	<script src="{% static 'js/app.min.js' %}"></script>
	<!-- ================== END core-js ================== -->
	
	{% block js %}{% endblock %}
</body>
</html>

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/pages/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home Page{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block content %}
	<ul class="breadcrumb">
		<li class="breadcrumb-item"><a href="#">BREADCRUMB</a></li>
		<li class="breadcrumb-item active">HOME PAGE</li>
	</ul>
	
	<h1 class="page-header">
		Starter Page <small>page header description goes here...</small>
	</h1>
	
	<p>
		Start build your page here
	</p>
{% endblock %}

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/pages/page-error.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Error Page{% endblock %}

{% block content %}
	<!-- BEGIN error -->
	<div class="error-page">
		<!-- BEGIN error-page-content -->
		<div class="error-page-content">
			<div class="card mb-5 mx-auto" style="max-width: 320px;">
				<div class="card-body">
					<div class="card">
						<div class="error-code">404</div>
						<div class="card-arrow">
							<div class="card-arrow-top-left"></div>
							<div class="card-arrow-top-right"></div>
							<div class="card-arrow-bottom-left"></div>
							<div class="card-arrow-bottom-right"></div>
						</div>
					</div>
				</div>
				<div class="card-arrow">
					<div class="card-arrow-top-left"></div>
					<div class="card-arrow-top-right"></div>
					<div class="card-arrow-bottom-left"></div>
					<div class="card-arrow-bottom-right"></div>
				</div>
			</div>
			<h1>Oops!</h1> 
			<h3>We can't seem to find the page you're looking for</h3>
			<hr>
			<p class="mb-1">
				Here are some helpful links instead:
			</p>
			<p class="mb-5">
				<a href="{% url 'DjangoHUDApp:index' %}" class="text-decoration-none text-inverse text-opacity-50">Home</a>
				<span class="link-divider"></span>
				<a href="{% url 'DjangoHUDApp:pageSearchResults' %}" class="text-decoration-none text-inverse text-opacity-50">Search</a>
				<span class="link-divider"></span>
				<a href="{% url 'DjangoHUDApp:emailInbox' %}" class="text-decoration-none text-inverse text-opacity-50">Email</a>
				<span class="link-divider"></span>
				<a href="{% url 'DjangoHUDApp:calendar' %}" class="text-decoration-none text-inverse text-opacity-50">Calendar</a>
				<span class="link-divider"></span>
				<a href="{% url 'DjangoHUDApp:settings' %}" class="text-decoration-none text-inverse text-opacity-50">Settings</a>
				<span class="link-divider"></span>
				<a href="{% url 'DjangoHUDApp:helper' %}" class="text-decoration-none text-inverse text-opacity-50">Helper</a>
			</p>
			<a href="javascript:window.history.back();" class="btn btn-outline-theme px-3 rounded-pill"><i class="fa fa-arrow-left me-1 ms-n1"></i> Go Back</a>
		</div>
		<!-- END error-page-content -->
	</div>
	<!-- END error -->
{% endblock %}

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/partial/footer.html
<div id="footer" class="app-footer">
	&copy; 2024 SeanTheme All Right Reserved
</div>

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/partial/header.html
<!-- BEGIN #header -->
<div id="header" class="app-header">
	{% if appSidebarHide is None %}
	<!-- BEGIN desktop-toggler -->
	<div class="desktop-toggler">
		<button type="button" class="menu-toggler" data-toggle-class="app-sidebar-collapsed" data-dismiss-class="app-sidebar-toggled" data-toggle-target=".app">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- BEGIN desktop-toggler -->
	
	<!-- BEGIN mobile-toggler -->
	<div class="mobile-toggler">
		<button type="button" class="menu-toggler" data-toggle-class="app-sidebar-mobile-toggled" data-toggle-target=".app">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- END mobile-toggler -->
	{% endif %}
	{% if appTopNav is not None and appSidebarHide %}
	<!-- BEGIN desktop-toggler -->
	<div class="desktop-toggler">
		<button type="button" class="menu-toggler">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- BEGIN desktop-toggler -->
	<!-- BEGIN mobile-toggler -->
	<div class="mobile-toggler">
		<button type="button" class="menu-toggler" data-toggle="app-top-nav-mobile">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</button>
	</div>
	<!-- END mobile-toggler -->
	{% endif %}
	
	<!-- BEGIN brand -->
	<div class="brand">
		<a href="/" class="brand-logo">
			<span class="brand-img">
				<span class="brand-img-text text-theme">H</span>
			</span>
			<span class="brand-text">HUD ADMIN</span>
		</a>
	</div>
	<!-- END brand -->
	
	<!-- BEGIN menu -->
	<div class="menu">
		<div class="menu-item dropdown">
			<a href="#" data-toggle-class="app-header-menu-search-toggled" data-toggle-target=".app" class="menu-link">
				<div class="menu-icon"><i class="bi bi-search nav-icon"></i></div>
			</a>
		</div>
		<div class="menu-item dropdown dropdown-mobile-full">
			<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
				<div class="menu-icon"><i class="bi bi-grid-3x3-gap nav-icon"></i></div>
			</a>
			<div class="dropdown-menu fade dropdown-menu-end w-300px text-center p-0 mt-1">
				<div class="row row-grid gx-0">
					<div class="col-4">
						<a href="/email/inbox" class="dropdown-item text-decoration-none p-3 bg-none">
							<div class="position-relative">
								<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
								<i class="bi bi-envelope h2 opacity-5 d-block my-1"></i>
							</div>
							<div class="fw-500 fs-10px text-inverse">INBOX</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/pos/customer-order" target="_blank" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-hdd-network h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">POS SYSTEM</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/calendar" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-calendar4 h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">CALENDAR</div>
						</a>
					</div>
				</div>
				<div class="row row-grid gx-0">
					<div class="col-4">
						<a href="/helper" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-terminal h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">HELPER</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/settings" class="dropdown-item text-decoration-none p-3 bg-none">
							<div class="position-relative">
								<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
								<i class="bi bi-sliders h2 opacity-5 d-block my-1"></i>
							</div>
							<div class="fw-500 fs-10px text-inverse">SETTINGS</div>
						</a>
					</div>
					<div class="col-4">
						<a href="/widgets" class="dropdown-item text-decoration-none p-3 bg-none">
							<div><i class="bi bi-collection-play h2 opacity-5 d-block my-1"></i></div>
							<div class="fw-500 fs-10px text-inverse">WIDGETS</div>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="menu-item dropdown dropdown-mobile-full">
			<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
				<div class="menu-icon"><i class="bi bi-bell nav-icon"></i></div>
				<div class="menu-badge bg-theme"></div>
			</a>
			<div class="dropdown-menu dropdown-menu-end mt-1 w-300px fs-11px pt-1">
				<h6 class="dropdown-header fs-10px mb-1">NOTIFICATIONS</h6>
				<div class="d-flex align-items-center py-10px dropdown-item text-wrap fs-6 bg-inverse bg-opacity-15 text-inverse text-opacity-50 h-100px">
					No record found
				</div>
				<hr class="my-0">
				<div class="py-10px mb-n2 text-center">
					<a href="#" class="text-decoration-none fw-bold">SEE ALL</a>
				</div>
			</div>
		</div>
		<div class="menu-item dropdown dropdown-mobile-full">
			<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
				<div class="menu-img online">
					<div class="d-flex align-items-center justify-content-center w-100 h-100 bg-inverse bg-opacity-25 text-inverse text-opacity-50 rounded-circle overflow-hidden">
						<i class="bi bi-person-fill fs-32px mb-n3"></i>
					</div>
				</div>
				<div class="menu-text d-sm-block d-none w-170px">username@account.com</div>
			</a>
			<div class="dropdown-menu dropdown-menu-end me-lg-3 fs-11px mt-1">
				<a class="dropdown-item d-flex align-items-center" href="/profile">PROFILE <i class="bi bi-person-circle ms-auto text-theme fs-16px my-n1"></i></a>
				<a class="dropdown-item d-flex align-items-center" href="/email/inbox">INBOX <i class="bi bi-envelope ms-auto text-theme fs-16px my-n1"></i></a>
				<a class="dropdown-item d-flex align-items-center" href="/calendar">CALENDAR <i class="bi bi-calendar ms-auto text-theme fs-16px my-n1"></i></a>
				<a class="dropdown-item d-flex align-items-center" href="/settings">SETTINGS <i class="bi bi-gear ms-auto text-theme fs-16px my-n1"></i></a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item d-flex align-items-center" href="/page/login">LOGOUT <i class="bi bi-toggle-off ms-auto text-theme fs-16px my-n1"></i></a>
			</div>
		</div>
	</div>
	<!-- END menu -->
	
	<!-- BEGIN menu-search -->
	<form class="menu-search" method="POST" name="header_search_form">
		<div class="menu-search-container">
			<div class="menu-search-icon"><i class="bi bi-search"></i></div>
			<div class="menu-search-input">
				<input type="text" class="form-control form-control-lg" placeholder="Search menu...">
			</div>
			<div class="menu-search-icon">
				<a href="#" data-toggle-class="app-header-menu-search-toggled" data-toggle-target=".app"><i class="bi bi-x-lg"></i></a>
			</div>
		</div>
	</form>
	<!-- END menu-search -->
</div>
<!-- END #header -->

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/partial/scroll-top-btn.html
<!-- BEGIN btn-scroll-top -->
		<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
		<!-- END btn-scroll-top -->

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/partial/sidebar.html
<!-- BEGIN #sidebar -->
<div id="sidebar" class="app-sidebar">
	<!-- BEGIN scrollbar -->
	<div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
		<!-- BEGIN menu -->
		<div class="menu">
			{% for menu in sidebar_menu %}
				{% if menu.is_header %}
					<div class="menu-header">{{ menu.text }}</div>
				{% elif menu.is_divider %}
					<div class="menu-divider"></div>
				{% else %}
					<div class="menu-item {% if menu.children %} has-sub {% endif %} {% if menu.is_active %} active {% endif %}">
						<a href="{{ menu.url }}" class="menu-link">
							<span class="menu-icon"><i class="{{ menu.icon }}"></i></span>
							<span class="menu-text">{{ menu.text }}</span>
							{% if menu.children %}
								<span class="menu-caret"><b class="caret"></b></span>
							{% endif %}
						</a>
						{% if menu.children %}
							<div class="menu-submenu">
								{% for children in menu.children %}
									<div class="menu-item {% if children.is_active %} active {% endif %}">
										<a href="{{ children.url }}" class="menu-link">
											<span class="menu-text">{{ children.text }}</span>
										</a>
									</div>
								{% endfor %}
							</div>
						{% endif %}
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<!-- END menu -->
		<div class="p-3 px-4 mt-auto">
			<a href="../../documentation/index.html" class="btn d-block btn-outline-theme">
				<i class="fa fa-code-branch me-2 ms-n2 opacity-5"></i> Documentation
			</a>
		</div>
	</div>
	<!-- END scrollbar -->
</div>
<!-- END #sidebar -->
	
<!-- BEGIN mobile-sidebar-backdrop -->
<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>
<!-- END mobile-sidebar-backdrop -->

theme/hud_django_v3.0/template_django_startup/DjangoHUDApp/templates/partial/theme-panel.html
{% load static %}
<!-- BEGIN theme-panel -->
<div class="app-theme-panel">
	<div class="app-theme-panel-container">
		<a href="javascript:;" data-toggle="theme-panel-expand" class="app-theme-toggle-btn"><i class="bi bi-sliders"></i></a>
		<div class="app-theme-panel-content">
			<div class="small fw-bold text-inverse mb-1">Display Mode</div>
			<div class="card mb-3">
				<!-- BEGIN card-body -->
				<div class="card-body p-2">
					<div class="row gx-2">
						<div class="col-6">
							<a href="javascript:;" data-toggle="theme-mode-selector" data-theme-mode="dark" class="app-theme-mode-link active">
								<div class="img"><img src="{% static 'img/mode/dark.jpg' %}" class="object-fit-cover" height="76" width="76" alt="Dark Mode"></div>
								<div class="text">Dark</div>
							</a>
						</div>
						<div class="col-6">
							<a href="javascript:;" data-toggle="theme-mode-selector" data-theme-mode="light" class="app-theme-mode-link">
								<div class="img"><img src="{% static 'img/mode/light.jpg' %}" class="object-fit-cover" height="76" width="76" alt="Light Mode"></div>
								<div class="text">Light</div>
							</a>
						</div>
					</div>
				</div>
				<!-- END card-body -->
				
				<!-- BEGIN card-arrow -->
				<div class="card-arrow">
					<div class="card-arrow-top-left"></div>
					<div class="card-arrow-top-right"></div>
					<div class="card-arrow-bottom-left"></div>
					<div class="card-arrow-bottom-right"></div>
				</div>
				<!-- END card-arrow -->
			</div>
			
			<div class="small fw-bold text-inverse mb-1">Theme Color</div>
			<div class="card mb-3">
				<!-- BEGIN card-body -->
				<div class="card-body p-2">
					<!-- BEGIN theme-list -->
					<div class="app-theme-list">
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-pink" data-theme-class="theme-pink" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Pink">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-red" data-theme-class="theme-red" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Red">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-warning" data-theme-class="theme-warning" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Orange">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-yellow" data-theme-class="theme-yellow" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Yellow">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-lime" data-theme-class="theme-lime" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Lime">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-green" data-theme-class="theme-green" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Green">&nbsp;</a></div>
						<div class="app-theme-list-item active"><a href="javascript:;" class="app-theme-list-link bg-teal" data-theme-class="" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Default">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-info" data-theme-class="theme-info"  data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cyan">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-primary" data-theme-class="theme-primary"  data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Blue">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-purple" data-theme-class="theme-purple" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Purple">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-indigo" data-theme-class="theme-indigo" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Indigo">&nbsp;</a></div>
						<div class="app-theme-list-item"><a href="javascript:;" class="app-theme-list-link bg-gray-100" data-theme-class="theme-gray-200" data-toggle="theme-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Gray">&nbsp;</a></div>
					</div>
					<!-- END theme-list -->
				</div>
				<!-- END card-body -->
				
				<!-- BEGIN card-arrow -->
				<div class="card-arrow">
					<div class="card-arrow-top-left"></div>
					<div class="card-arrow-top-right"></div>
					<div class="card-arrow-bottom-left"></div>
					<div class="card-arrow-bottom-right"></div>
				</div>
				<!-- END card-arrow -->
			</div>
			
			<div class="small fw-bold text-inverse mb-1">Theme Cover</div>
			<div class="card">
				<!-- BEGIN card-body -->
				<div class="card-body p-2">
					<!-- BEGIN theme-cover -->
					<div class="app-theme-cover">
						<div class="app-theme-cover-item active">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-1.jpg' %});" data-theme-cover-class="" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Default">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-2.jpg' %});" data-theme-cover-class="bg-cover-2" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 2">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-3.jpg' %});" data-theme-cover-class="bg-cover-3" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 3">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-4.jpg' %});" data-theme-cover-class="bg-cover-4" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 4">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-5.jpg' %});" data-theme-cover-class="bg-cover-5" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 5">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-6.jpg' %});" data-theme-cover-class="bg-cover-6" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 6">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-7.jpg' %});" data-theme-cover-class="bg-cover-7" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 7">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-8.jpg' %});" data-theme-cover-class="bg-cover-8" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 8">&nbsp;</a>
						</div>
						<div class="app-theme-cover-item">
							<a href="javascript:;" class="app-theme-cover-link" style="background-image: url({% static 'img/cover/cover-thumb-9.jpg' %});" data-theme-cover-class="bg-cover-9" data-toggle="theme-cover-selector" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-container="body" data-bs-title="Cover 9">&nbsp;</a>
						</div>
					</div>
					<!-- END theme-cover -->
				</div>
				<!-- END card-body -->
				
				<!-- BEGIN card-arrow -->
				<div class="card-arrow">
					<div class="card-arrow-top-left"></div>
					<div class="card-arrow-top-right"></div>
					<div class="card-arrow-bottom-left"></div>
					<div class="card-arrow-bottom-right"></div>
				</div>
				<!-- END card-arrow -->
			</div>
		</div>
	</div>
</div>
<!-- END theme-panel -->